name: Build & Publish

on:
  workflow_dispatch:

jobs:
  BuildAndPublish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build Myra
      run: dotnet build src\Myra\Myra.csproj --configuration Release
    - name: Build Myra.MonoGame
      run: dotnet build src\XNA\Myra.MonoGame.csproj --configuration Release
    - name: Build Myra.Stride
      run: dotnet build src\XNA\Myra.Stride.csproj --configuration Release
